### ISSUE TITLE
Support for returning a tool result

### ISSUE THREAD

**Issue by philpax** [cortesi/misanthropy#1]
Hi there!

First off, I just wanted to express my regards for creating the best Anthropic API client I've seen so far - early days but I hope for the best, especially with the new rush of excitement around 3.5 Sonnet 🙂 

Anyhow, I noticed that the library only supports one half of the tool calling interaction at this point (as far as I can tell) - there's no way to supply a tool call result after a request. From looking at [the docs](https://docs.anthropic.com/en/docs/build-with-claude/tool-use#single-tool-example), I think this is as easy as adding `ToolResult(ToolResult { tool_use_id: String, content: String })` to `misanthropy::Content`.

I can do this tomorrow in a PR, but I just wanted to check in and see if you had any plans for this before I do it (including updating examples and docs). Cheers 🚀

**Comment by cortesi** [comment]
Thanks for the report! Yes, that's a bit of an oversight. :) I have seen your PR - it looks good at first blush, but I want to think about the Clone on MessagesRequest. I'll merge tomorrow.
